# Generated by Django 4.2.4 on 2023-12-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(default='Название болезни', max_length=150)),
                ('general_info', models.CharField(default='Общая информация о болезни', max_length=255)),
                ('simptoms', models.CharField(default='Симптомы', max_length=255)),
                ('image', models.TextField(default=b'')),
                ('status', models.CharField(choices=[('a', 'active'), ('d', 'delited')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Заболевания',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiseaseDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.disease')),
            ],
            options={
                'verbose_name_plural': 'Заболевание-препарат',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('sphere_id', models.AutoField(primary_key=True, serialize=False)),
                ('sphere_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Сфера применения',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medical_drug',
            fields=[
                ('drug_id', models.AutoField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(default='Название лекарства', max_length=150)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_form', models.DateTimeField(auto_now=True)),
                ('time_finish', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('e', 'Черновик'), ('o', 'В работе'), ('f', 'Завершён'), ('c', 'Отменён'), ('d', 'Удалён')], default='e', max_length=1)),
                ('for_disease', models.ManyToManyField(through='list_of_diseases.DiseaseDrug', to='list_of_diseases.disease')),
                ('sphere_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.sphere')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.user')),
            ],
            options={
                'verbose_name_plural': 'Медицинские препараты',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='diseasedrug',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.medical_drug'),
        ),
        migrations.AddField(
            model_name='disease',
            name='sphere_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.sphere'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('password', models.TextField(max_length=256, verbose_name='Пароль')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
