# Generated by Django 4.2.4 on 2023-10-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(default='Название болезни', max_length=150)),
                ('general_info', models.CharField(default='Общая информация о болезни', max_length=255)),
                ('simptoms', models.CharField(default='Симптомы', max_length=255)),
                ('image', models.BinaryField(default=b'')),
                ('status', models.CharField(choices=[('a', 'active'), ('d', 'delited')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Заболевания',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DiseaseDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.disease')),
            ],
            options={
                'verbose_name_plural': 'Заболевание-препарат',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('sphere_id', models.AutoField(primary_key=True, serialize=False)),
                ('sphere_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Сфера применения',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Medical_drug',
            fields=[
                ('drug_id', models.AutoField(default=-1, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(default='Название лекарства', max_length=150)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_form', models.DateTimeField(auto_now=True)),
                ('time_finish', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('e', 'Введён'), ('o', 'В работе'), ('f', 'Завершён'), ('c', 'Отменён'), ('d', 'Удалён')], default='e', max_length=1)),
                ('for_disease', models.ManyToManyField(through='list_of_diseases.DiseaseDrug', to='list_of_diseases.disease')),
                ('sphere_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.sphere')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.user')),
            ],
            options={
                'verbose_name_plural': 'Медицинские препараты',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='diseasedrug',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.medical_drug'),
        ),
        migrations.AddField(
            model_name='disease',
            name='sphere_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.sphere'),
        ),
    ]
