# Generated by Django 4.2.4 on 2023-09-26 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sphere',
            fields=[
                ('sphere_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sphere_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Сфера применения',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=150)),
                ('general_info', models.CharField(max_length=255)),
                ('simptoms', models.CharField(max_length=255)),
                ('image', models.TextField(default='')),
                ('status', models.CharField(choices=[('a', 'active'), ('d', 'delited')], max_length=1)),
                ('sphere_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.sphere')),
            ],
            options={
                'verbose_name_plural': 'Заболевания',
            },
        ),
        migrations.CreateModel(
            name='DiseaseDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.disease')),
            ],
            options={
                'verbose_name_plural': 'Заболевание-препарат',
            },
        ),
        migrations.CreateModel(
            name='Medical_drug',
            fields=[
                ('drug_id', models.IntegerField(primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=150)),
                ('time_create', models.DateTimeField(auto_now=True)),
                ('time_form', models.DateTimeField(auto_now=True)),
                ('time_finish', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('e', 'entered'), ('o', 'in operation'), ('f', 'finished'), ('c', 'cancelled'), ('d', 'deleted')], max_length=1)),
                ('for_disease', models.ManyToManyField(through='list_of_diseases.DiseaseDrug', to='list_of_diseases.disease')),
                ('sphere_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.sphere')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.user')),
            ],
            options={
                'verbose_name_plural': 'Медицинские препараты',
            },
        ),
        migrations.AddField(
            model_name='diseasedrug',
            name='drug_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.medical_drug'),
        ),
    ]
