# Generated by Django 4.2.4 on 2023-09-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_test',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
