# Generated by Django 4.2.4 on 2023-10-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='list_of_diseases/static/images'),
        ),
    ]
