# Generated by Django 4.2.4 on 2023-10-14 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0002_alter_disease_disease_id_alter_medical_drug_drug_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_drug',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.user'),
        ),
    ]
