# Generated by Django 4.2.4 on 2023-09-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0002_user_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_test',
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'managed': True, 'verbose_name_plural': 'Заболевания'},
        ),
        migrations.AlterModelOptions(
            name='diseasedrug',
            options={'managed': True, 'verbose_name_plural': 'Заболевание-препарат'},
        ),
        migrations.AlterModelOptions(
            name='medical_drug',
            options={'managed': True, 'verbose_name_plural': 'Медицинские препараты'},
        ),
        migrations.AlterModelOptions(
            name='sphere',
            options={'managed': True, 'verbose_name_plural': 'Сфера применения'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='disease',
            name='image',
            field=models.ImageField(upload_to='list_of_diseases/static/images'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='sphere_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.sphere'),
        ),
        migrations.AlterField(
            model_name='medical_drug',
            name='sphere_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list_of_diseases.sphere'),
        ),
        migrations.AlterField(
            model_name='medical_drug',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
