# Generated by Django 4.2.4 on 2023-12-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0003_alter_disease_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasedrug',
            options={'managed': True, 'verbose_name_plural': 'Заболевания-препараты'},
        ),
    ]
