# Generated by Django 4.2.4 on 2023-10-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0003_alter_medical_drug_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_drug',
            name='status',
            field=models.CharField(choices=[('e', 'Черновик'), ('o', 'В работе'), ('f', 'Завершён'), ('c', 'Отменён'), ('d', 'Удалён')], default='e', max_length=1),
        ),
    ]
