# Generated by Django 4.2.4 on 2023-12-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0004_alter_diseasedrug_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
