# Generated by Django 4.2.4 on 2023-12-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0005_alter_customuser_options_customuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
