# Generated by Django 4.2.4 on 2023-12-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=30, verbose_name='Имя пользователя'),
        ),
    ]
