# Generated by Django 5.0 on 2023-12-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_drug',
            name='test_status',
            field=models.IntegerField(choices=[(0, 'Не удалось обратиться к асинхронному сервису'), (1, 'Успех'), (2, 'Неуспех')], default=1),
        ),
    ]
