# Generated by Django 5.0 on 2023-12-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_of_diseases', '0009_alter_customuser_options_medical_drug_moderator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_drug',
            name='moderator',
        ),
    ]
